### ISSUE TITLE
Question: How to pickup / harvest?

### ISSUE THREAD

**Issue by himpich** [Xeio/MassFarming#1]
Thanks for your addon. The planting part is working great for me but I can't figure out, how to mass-harvest.
* I tried to focus an item I want to harvest and press the key
* I tried to just press the key

How does it work? :)

Thanks in advance

**Comment by Xeio** [comment]
Hold the modifier key, then press your normal "harvest" button.

It's a little more obvious when planting, since the extra plants only show a preview when holding the button.

**Comment by himpich** [comment]
awww... Love it. This is perfect, thanks. 

You might want to clarify it in the README - this is great!
