### ISSUE TITLE
Planting Grid Broken after Patch 0.216.9

### ISSUE THREAD

**Issue by SamSchuddinck** [Xeio/MassFarming#13]
The planting grid seems to be broken after Valheim patch update 0.216.9
Picking up however still seems to be working.

**Comment by SaltiDawg** [comment]
Also having this same issue

**Comment by BrianBCG** [comment]
Me too, I don't know if I can live without this feature anymore. I just stopped farming altogether ;)

**Comment by yolanv** [comment]
@Xeio any ETA on a fix for this?

**Comment by Xeio** [comment]
See release v1.7

**Comment by yolanv** [comment]
Legend.
