### ISSUE TITLE
Grid planting is not working after Hildir's Request update

### ISSUE THREAD

**Issue by Liora42** [Xeio/MassFarming#18]
Hello, 

Since the update, holding shift to place plants in a grid will show the plants in a 5x5 grid, but left clicking will only plant one plant (the plant in the center. I made sure that I had plenty of stamina, and MassFarming was the only mod installed.

In the Bepinex log, I am getting this error over and over:

[Error  : Unity Log] MissingFieldException: Field 'PlayerProfile/PlayerStats.m_builds' not found.
Stack trace:
(wrapper dynamic-method) Player.DMD<Player::UpdatePlacement>(Player,bool,single)
Player.Update () (at <447b19510f604ca3807cd6cce3a7c1ef>:0)

Let me know if you need any more information.

**Comment by herrhamilton** [comment]
They fixed it in 1.8: https://github.com/Xeio/MassFarming/releases/tag/v1.8

**Comment by Liora42** [comment]
> They fixed it in 1.8: https://github.com/Xeio/MassFarming/releases/tag/v1.8

Thanks, I hadn't seen that!
