### ISSUE TITLE
Mass Plant Not Working

### ISSUE THREAD

**Issue by Toast-Crumbs** [Xeio/MassFarming#2]
Hey, thank you for the mod, i love it! However, for some reason my ability to mass plant has stopped working. When I hit the modifier button the crops show up like they're all going to be planted in the grid as I've specified in the config file (10x10) but when i plant the crops only 1 or two plants will plant. Typically it's the main crop and then a random one towards the edge. I've tried deleting the config and .dll file and then re-downloading and re-installing, but it did not work. Not really sure what else to try, might be a conflict with another mod but I'm not sure. Thanks again!

**Comment by Xeio** [comment]
Hmmm, do they show as red when you preview placing them, or do they just not place when you attempt to place them? Seems some people have issues with "infinite durability" items from another mod, though you can turn durability checks off on MassFarming if that's the issue with the F1 menu.

**Comment by Toast-Crumbs** [comment]
No, the crops are green whenever I go to plant them. I attached a video for you to see. I'll try turning the infinite durability checks off and report back. Thanks!

[MassFarmingBug.zip](https://github.com/Xeio/MassFarming/files/6267657/MassFarmingBug.zip)

**Comment by Toast-Crumbs** [comment]
I changed the infinite durability when farming to true from false in the config file and it seemed to have fixed the issue I was having. Thanks!
