### ISSUE TITLE
19 Nov update not making the mod work properly

### ISSUE THREAD

**Issue by Marvincf2** [Xeio/MassFarming#28]
After the recent nov 19 patch the shift farm placement does not work anymore. I can't plant seeds with the shift key , however i can still shift- pickup stuff.

**Comment by MarkZetsu** [comment]
BepInEx is showing the following when trying to plant. 

![image](https://github.com/user-attachments/assets/0a2784da-0785-497b-ae5f-bd0214265cc2)

**Comment by Milster** [comment]
Can confirm the error log. Fixed it for myself by replacing the __fixedPiece by an instantiation of the first piece we encounter, but this isn't a real fix because it causes one fake plant on the ground and two (ignored) exceptions.

**Comment by pewnl** [comment]
Same error, hoping for an update soon <3

**Comment by Xeio** [comment]
Should be fixed in version 1.11
