### ISSUE TITLE
Hearth and home

### ISSUE THREAD

**Issue by wwray** [Xeio/MassFarming#3]
the mod doesn't appear to be working after the hearth and home update. I absolutely adore this mod, I hope you can update it to work! Thanks

**Comment by jammons** [comment]
I just got the latest code to build, and it works fine in Hearth and Home, make sure you are loading version 1.3 of the mod. The version in the r2modman repository was old, but it looks like someone uploaded the latest version under a different author. Nexusmods looks like it has the latest build: https://www.nexusmods.com/valheim/mods/527

**Comment by wwray** [comment]
fantastic, thanks for pointing that out. I found the new addon under the different author and it works great!
